baseurl = "https://dosbox-x.virtualhub.eu.org"
metaDataFormat = "yaml"
title = "VirtualHub DOSBox-X"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[params]
  introTitle = "Welcome to VirtualHub DOSBox-X!"
  introSubtitle = "Install old software on your new system using DOSBox-X!"
  introPhoto = "/dosbox-x.png"
  logo = ""

  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Legacy Installer · All rights reserved"
  favicon = "/logo.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "posts"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow us"
  description = "Follow us to know how to install old software and OS in may different ways."
  twitter = "https://twitter.com/virtua1hub"
  github = "https://github.com/InstallerLegacy"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "contact"
  weight = 4

[[menu.main]]
  name = "Our Other Websites"
  url = "other-websites"
  weight = 5

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
